define(
    {
        invalidMessageName: "Invalid data in this field.",
        missingMessageName: "Fill this field.",		  
        promptMessageName: "dd/mm/yyyy",
		  lcabeceraadd: "Donor Creation",
		  lcabeceradel: "Delete Donor",
		  lcabeceralist: "Donors List",
		  lcabeceraprb: "Test Settings",
        ltit1: "Donor Information",
        ltit2: "Clinical Data",
        ltit3: "Test Data",
        lnombre: "Name",
        lape1: "Surname 1",
        lape2: "Surname 2",
        lnombrecompleto: "Name SurN1 SurN2",
        lfnac: "DOB",
        ldni: "PID",
        ledad: "Age",
        lsexo: "Sex",
        ldomic: "Home Address",
        lciudad: "City",
        lregion: "State",
        lpais: "Country",
        ltlf: "Phone",
        lmov: "Cell Phone",
        lemail: "e-mail",
        lestado: "Status",
        liclinic: "Clinical Data",
        lafam: "Family background",
        lsi: "Ok",
        lno: "Cancel",
        ldonante: "Donor",
        lojo: "Warning",
		  lstatus: "Status",
        lfiltro: "Filter",
		  lanalitica: "Test",
		  lsol: "Requests",
		  lres: "Results",
		  lprb: "Testing",
		  lped: "Requested",
		  ldesc: "Description",
		  lunidades: "Units"	             
    }
);