define({ root:
	({
        invalidMessageName: "Datos invalidos para este campo.",
        missingMessageName: "Rellene el campo.",
        promptMessageName: "dd/mm/yyyy",
        lcabeceraadd: "Creación del Donante",
		  lcabeceradel: "Borrar Donante",
		  lcabeceralist: "Lista de Donantes",
		  lcabeceraprb: "Configuración Pruebas",
        ltit1: "Datos del Donante",
        ltit2: "Datos Clínicos",
        ltit3: "Datos de la Prueba",
        lnombre: "Nombre",
        lape1: "Apellido 1",
        lape2: "Apellido 2",
        lnombrecompleto: "Nombre Ape1 Ape2",
        lfnac: "F. Nacimiento",
        ldni: "DNI",
        ledad: "Edad",
        lsexo: "Sexo",
        ldomic: "Domicilio",
        lciudad: "Ciudad",
        lregion: "Region",
        lpais: "Pais",
        ltlf: "Teléfono",
        lmov: "Movil",
        lemail: "e-mail",
        lestado: "Estado",
        liclinic: "Información Clínica",
        lafam: "Antecedentes Familiares",
        lsi: "Aceptar",
        lno: "Cancelar",
        ldonante: "Donante",
        lojo: "Advertencia",
        lstatus: "Estado",
        lfiltro: "Filtro",
		  lanalitica: "Analítica",
		  lsol: "Solicitudes",
		  lres: "Resultados",
		  lprb: "Pruebas",
		  lped: "Pedidas",
		  ldesc: "Descripción",
		  lunidades: "Unidades"	  
	}),
"es-es": true,
"en-us": true
});
